// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Account struct {
	ID        string
	Balance   int64
	Currency  string
	CreatedAt time.Time
}
